version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: post_office_db
    environment:
      POSTGRES_DB: post_office_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: